config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'locations#index'
  resources :locations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index 
    @locations = Location.all
  end

  def new
    @location = Location.new
  end

  def create
    Location.create(location_params)
    redirect_to root_path
  end

  def location_params
    params.require(:location).permit(:name, :description, :address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plygrnd</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/index.html.erb
<h1>Welcome to my New App</h1>

<br>
<br>

<h3>I am not entirely sure what I am building, but either way it will be amazing!!!</h3>

<div class="text-center">
  <button type="button" class="btn btn-lg.round">
    <%= link_to 'Add a New Location!', new_location_path %>
    </button>
</div>


<hr>
<hr>
<hr>

<% @locations.each do |location| %>
  <div class="booyah-box col-10 offset-1">
    <h1><%= location.name %></h1><br />
    <p><%= location.description %></p><br />
    <i><%= location.description %></p>
  </div>
<% end %> 

app/views/locations/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Playground Info</h1>
   <%= simple_form_for @location do |f| %>
     <%= f.input :name %>
     <%= f.input :description %>
     <%= f.input :address %>
     <br />
     <%= f.submit 'Create', class: 'btn btn-primary' %>
   <% end %>
</div>